#include <gtest/gtest.h>
#include "cho_hardware_openarm_mit_mujoco/mit_limiter.hpp"
using namespace cho_hardware_openarm_mit_mujoco;
namespace {auto profile(){return cho_openarm_mit_core::load_safety_profile_file(OPENARM_SAFETY_PROFILE_SOURCE,"mujoco_sim_safe",cho_openarm_mit_core::SafetyBackend::MUJOCO);}}
TEST(MitLimiter, RequiresExplicitProfileRate){auto p=profile();EXPECT_THROW(Limiter l(p,999),std::invalid_argument);Limiter l(p,1000);}
TEST(MitLimiter, EquationAndPureTorque){auto p=profile();Limiter l(p,1000);std::array<double,N>q{},dq{};l.reset(q);std::array<Tuple,N>c{};for(auto&x:c)x={1,.5,2,3,4};ASSERT_TRUE(l.submit(c,1,5));auto t=l.update(q,dq,1);for(std::size_t i=0;i<N;++i){double target=std::max(p.position_lower[i],std::min(1.0,p.position_upper[i]));double expected=2*target+std::min(3.0,p.kd_max[i])*.5+std::min(4.0,p.tau_ff_max[i]);EXPECT_DOUBLE_EQ(t[i],expected);}for(auto&x:c)x={0,0,0,0,1};ASSERT_TRUE(l.submit(c,2,5));t=l.update(q,dq,1);for(auto x:t)EXPECT_DOUBLE_EQ(x,1);}
TEST(MitLimiter, ClampSlewLeaseAndFaultSafe){Limiter l(profile(),1000);std::array<double,N>q{},dq{};l.reset(q);std::array<Tuple,N>c{};for(auto&x:c)x={99,99,99,99,99};ASSERT_TRUE(l.submit(c,1,2));auto t=l.update(q,dq,.001);for(auto x:t)EXPECT_LE(std::abs(x),.2);t=l.update(q,dq,.001);EXPECT_TRUE(l.safe());l.reset(q);ASSERT_TRUE(l.submit(c,1,5));l.fault();t=l.update(q,dq,.001);EXPECT_TRUE(l.safe());}
TEST(MitLimiter, RejectInvalidReplayAndLease){Limiter l(profile(),1000);std::array<double,N>q{};l.reset(q);std::array<Tuple,N>c{};EXPECT_FALSE(l.submit(c,0,1));EXPECT_FALSE(l.submit(c,1,0));EXPECT_TRUE(l.submit(c,1,2));EXPECT_FALSE(l.submit(c,1,2));c[3].kp=-1;EXPECT_FALSE(l.submit(c,2,2));EXPECT_EQ(l.ack(),1u);}
TEST(MitLimiter, UsesProfileLeaseCapAndRejectedCommandDoesNotReplaceAccepted){auto p=profile();Limiter l(p,1000);std::array<double,N>q{},dq{};l.reset(q);std::array<Tuple,N>c{};for(auto&x:c)x={0,0,0,0,1};ASSERT_TRUE(l.submit(c,1,p.lease_cap));auto before=l.update(q,dq,1);for(auto&x:c)x.tau=2;c[0].kp=-1;EXPECT_FALSE(l.submit(c,2,p.lease_cap));auto after=l.update(q,dq,1);EXPECT_EQ(l.ack(),1u);EXPECT_EQ(before,after);EXPECT_FALSE(l.submit(c,2,p.lease_cap+1));}
TEST(MitLimiter, ExplicitSafeCapturesMeasuredPositionInsteadOfStaleTarget){Limiter l(profile(),1000);std::array<double,N>q{},dq{};l.reset(q);std::array<Tuple,N>c{};for(auto&x:c)x={1,0,5,.5,0};ASSERT_TRUE(l.submit(c,1,20));(void)l.update(q,dq,1);q.fill(.4);l.request_safe();auto tau=l.update(q,dq,1);for(double value:tau)EXPECT_NEAR(value,0,1e-12);}
TEST(MitLimiter, SafeHoldRetainsLastAcceptedFeedforward){Limiter l(profile(),1000);std::array<double,N>q{},dq{};l.reset(q);std::array<Tuple,N>c{};for(auto&x:c)x={0,0,0,0,1};ASSERT_TRUE(l.submit(c,1,20));(void)l.update(q,dq,1);l.request_safe();/* SAFE keeps the last accepted tau_ff around the captured position: the MIT motor has no gravity model */auto tau=l.update(q,dq,1);EXPECT_TRUE(l.safe());for(double value:tau)EXPECT_NEAR(value,1,1e-12);}
