# Copyright 2026 Hyunho Cho
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

cmake_minimum_required(VERSION 3.8)
project(cho_moveit_common)

find_package(ament_cmake REQUIRED)

if(BUILD_TESTING)
  find_package(ament_cmake_pytest REQUIRED)
  set(ENV{PYTEST_DISABLE_PLUGIN_AUTOLOAD} 1)
  ament_add_pytest_test(moveit_action_bridge_tests
    test/test_moveit_action_bridge.py
    APPEND_ENV PYTEST_DISABLE_PLUGIN_AUTOLOAD=1
  )
  ament_add_pytest_test(moveit_action_bridge_parameter_tests
    test/test_moveit_action_bridge_parameters.py
    APPEND_ENV PYTEST_DISABLE_PLUGIN_AUTOLOAD=1
    ENV ROS_DOMAIN_ID=223
  )
  ament_add_pytest_test(static_scene_parameter_tests
    test/test_publish_static_scene_parameters.py
    APPEND_ENV PYTEST_DISABLE_PLUGIN_AUTOLOAD=1
    ENV ROS_DOMAIN_ID=223
  )
endif()

install(PROGRAMS
  scripts/moveit_action_bridge.py
  scripts/publish_static_scene.py
  scripts/wait_for_static_scene.py
  DESTINATION lib/${PROJECT_NAME}
)

ament_package()
