#!/usr/bin/env python3
"""Generate a cuRobo robot config yml from an XRDF, with a velocity ceiling.

Why this exists
---------------
cuMotion plans from an XRDF plus the URDF and never reads MoveIt's
`joint_limits.yaml`. cuRobo's XRDF parser (`curobo/util/xrdf_utils.py`) accepts
only `acceleration_limits` and `jerk_limits`; **velocity comes from the URDF**.

For FR5 that is a problem. The URDF carries the datasheet maxima (3.15 / 3.2
rad/s) while this cell's commissioned ceiling is half that (1.575 / 1.6) and
lives only in `cho_moveit_fr5/config/joint_limits.yaml`. At the project's
standard 0.25 scaling, cuMotion would therefore command 3.15 * 0.25 = 0.7875
rad/s -- the exact value that file records the real FR5 refusing with
`ServoJ refused, code 14 (ERR_EXECUTION_FAILED)`.

cuRobo does support a `velocity_scale` on its cspace config, but only the yml
robot-config format can carry it. So: keep the XRDF as the single authored
source for geometry, convert it here, and inject the scale. Nothing upstream is
patched (todo/CUROBO_MOVEIT_TODO.md D6).

The generated yml is a build artifact, not a source file. Write it to a temp
path at launch time and hand it to the planner node's `yml_file_path` parameter.

Usage
-----
    curobo_robot_config.py --xrdf <file> --urdf <file> --velocity-scale 0.5 \
        --out /tmp/fr5_curobo.yml

Run it with the interpreter that has cuRobo installed
(`~/ros2_ws/.venv-curobo/bin/python`), not the system python.
"""

import argparse
from pathlib import Path
import sys

import yaml


def build_config(xrdf_path, urdf_path, velocity_scale, acceleration_scale=None):
    """Convert XRDF + URDF into a cuRobo robot config dict with a velocity scale."""
    # Imported here so --help works without cuRobo present.
    from curobo.cuda_robot_model.util import load_robot_yaml
    from curobo.types.file_path import ContentPath

    config = load_robot_yaml(ContentPath(
        robot_xrdf_absolute_path=str(xrdf_path),
        robot_urdf_absolute_path=str(urdf_path),
    ))

    cspace = config['robot_cfg']['kinematics']['cspace']
    cspace['velocity_scale'] = velocity_scale
    if acceleration_scale is not None:
        cspace['acceleration_scale'] = acceleration_scale

    # The absolute URDF path has to survive into the yml: the planner node's yml
    # branch only overrides it when `urdf_path` is also passed as a parameter.
    config['robot_cfg']['kinematics']['urdf_path'] = str(urdf_path)
    return config


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--xrdf', required=True, type=Path)
    parser.add_argument('--urdf', required=True, type=Path)
    parser.add_argument(
        '--velocity-scale', type=float, required=True,
        help='multiplies the URDF velocity limits. For FR5 use 0.5, which turns '
             'the datasheet 3.15 rad/s into the commissioned 1.575 rad/s '
             '(see cho_moveit_fr5/config/joint_limits.yaml).')
    parser.add_argument(
        '--acceleration-scale', type=float, default=None,
        help='optional; the XRDF already states absolute acceleration limits, '
             'so normally leave this unset')
    parser.add_argument('--out', required=True, type=Path)
    args = parser.parse_args()

    for path in (args.xrdf, args.urdf):
        if not path.is_file():
            parser.error(f'not a file: {path}')
    if not 0.0 < args.velocity_scale <= 1.0:
        parser.error('--velocity-scale must be in (0, 1]')

    config = build_config(args.xrdf, args.urdf,
                          args.velocity_scale, args.acceleration_scale)

    args.out.parent.mkdir(parents=True, exist_ok=True)
    header = (
        '# GENERATED by cho_moveit_common/scripts/curobo_robot_config.py.\n'
        '# Do not edit and do not commit: edit the XRDF instead.\n'
        f'#   xrdf:           {args.xrdf}\n'
        f'#   urdf:           {args.urdf}\n'
        f'#   velocity_scale: {args.velocity_scale}\n'
    )
    with args.out.open('w', encoding='utf-8') as handle:
        handle.write(header)
        yaml.safe_dump(config, handle, default_flow_style=None, sort_keys=False)

    kinematics = config['robot_cfg']['kinematics']
    print(f'wrote {args.out}')
    print(f"  ee_link         : {kinematics.get('ee_link')}")
    print(f"  base_link       : {kinematics.get('base_link')}")
    print(f"  velocity_scale  : {kinematics['cspace']['velocity_scale']}")
    print(f"  max_acceleration: {kinematics['cspace'].get('max_acceleration')}")
    print(f"  max_jerk        : {kinematics['cspace'].get('max_jerk')}")
    return 0


if __name__ == '__main__':
    sys.exit(main())
